#!/usr/local/bin/perl
eval "exec /usr/local/bin/perl -S $0 $*"
    if $running_under_some_shell;
			# this emulates #! processing on NIH machines.
			# (remove #! line above if indigestible)

eval '$'.$1.'$2;' while $ARGV[0] =~ /^([A-Za-z_]+=)(.*)/ && shift;
			# process any FOO=bar switches

while (<>) {
    ($Fld1,$Fld2,$Fld3) = split(' ', $_, 6);

    if ($Fld3 =~ '[0-9]*K') {
	@a = split(/K/, $Fld3, 3);
	$sum += $a[0] * 1024;
    }
    else {
	$sum += $Fld3;
    }
}

printf "%dK\n", $sum / 1024;

