#!/bin/sh

#   Программа завершения изменений в законах


cd $HOMEZAKON

if [[ ! -d diffs ]]
then
  echo error: diffs not exist
  exit 1
fi

if [[ ! -r diffs/old_dir ]]
then
  echo error: startpatch didn\'t work here
  exit 1
fi

# получаем имена новых файлов
find zakon -name '*' -print|sort > diffs/new_dir

# генерируем имена очередных patch'ей
touch diffs/patch.000

NEXTPATCH=`ls -r diffs/patch*|head -1|awk -F. '{printf "%s.%03s", $1, $2+1}'`
NEXTNEW=`ls -r diffs/patch*|head -1|\
		awk -F. '{printf "diffs/newfiles.%03s", $2+1}'`
NEXTZIPNEW=`ls -r diffs/patch*|head -1|awk -F. '{printf "diffs/patn%03s.zip", $2+1}'`
NEXTZIPPATCH=`ls -r diffs/patch*|head -1|\
		awk -F. '{printf "diffs/patp%03s.zip", $2+1}'`

rm diffs/patch.000

echo $NEXTPATCH >&2
echo $NEXTNEW >&2
echo $NEXTZIPNEW >&2
echo $NEXTZIPPATCH >&2

# попутно обрезаем старые файлы      vvvvvvvvvvvvv
comm -23 diffs/new_dir diffs/old_dir|grep "\.hyp$" > diffs/patch.000
comm -23 diffs/new_dir diffs/old_dir|grep "\.vzk$" >> diffs/patch.000
comm -23 diffs/new_dir diffs/old_dir|grep "\.[rpv]ps$" >> diffs/patch.000
sort diffs/patch.000 > $NEXTNEW

# a теперь генерим сам patch       vvvvvvvvvvvvvvvvvv - это не измененные файлы
gdiff +recursive diffs/zakon zakon|grep -v "Only in " | 
	grep -v '^< ' | grep -v '^---$'> $NEXTPATCH
cat $NEXTPATCH | grep ^diff | awk '{print $4}' | sort > diffs/patch.000

zip $NEXTZIPNEW `cat $NEXTNEW`
zip $NEXTZIPPATCH `comm -23 diffs/patch.000 $NEXTNEW`

rm -f diffs/patch.000

l $NEXTZIPNEW $NEXTZIPPATCH
